server:
  port: 8081

spring:
  application:
    name: activiti-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  activiti:
    check-process-definitions: false
    font:
      activityFontName: 宋体
      labelFontName: 宋体

